export const TEXTS_CZ = {
  header: {
    logoSubtext: "online kuchařka",
    loginButton: "Přihlásit se",
    languageCz: "CZ",
    languageEn: "EN",
    profileButton: "Profil",
  },
  navigation: {
    recipes: "Domů",
    categories: "Kategorie",
    create: "Vytvořit recept",
    favorites: "Oblíbené",
    my: "Moje recepty",
  },
  hero: {
    title: "Už vás nebaví vymýšlet, ",
    titleAccent: "co vařit?",
    titleSubtext: "Podívejte se na recepty nebo přidejte svůj vlastní!",
  },
  categories: {
    title: "Recepty",
    search: "Hledat",
    filters: "Filtry",
    categories: "Kategorie",
    diet: "Stravování",
    time: "Doba přípravy",
    score: "Hodnocení",
    clearFilters: "Zrušit filtry",
    applyFilters: "Použít filtry",
  },
  tags: {
    breakfast: "Snídaně",
    lunch: "Oběd",
    dinner: "Večeře",
    desserts: "Dezerty",
    snacks: "Svačiny",
    vegan: "Vegan",
    vegeterian: "Vegetariánské",
    glutenFree: "Bezlepkové",
  },
  preparationTime: {
    upTo15: "Do 15 minut",
    upTo30: "Do 30 minut",
    moreThan30: "Více než 30 minut",
  },
  rating: {
    more: "a více",
  },
  createRecipe: {
    createRecipe: "Vytvořit recept",
    form: {
      sections: {
        basic: "Základní informace",
        ingredients: "Ingredience",
        steps: "Postup",
        images: "Obrázky",
      },
      fields: {
        name: "Název receptu",
        description: "Popis",
        time: "Doba přípravy (min)",
        servings: "Počet porcí",
        category: "Kategorie",
        uploadImages: "Nahrát obrázky",
      },
      placeholders: {
        name: "Např. Krémové těstoviny s houbami",
        description: "Krátký popis receptu",
        category: "Vyberte kategorii",
        ingredient: "Např. 200 g těstovin",
        step: "Krok",
        amount: "Množství",
        unit: "Jednotka",
        ingredientName: "Např. těstoviny",
      },
      hints: {
        ingredients:
          "Tip: přidejte jednu položku na řádek — nové pole se objeví automaticky 😉",
        imagesEmpty: "PNG/JPG/WebP",
        imagesSelected: "Vybráno souborů",
      },
      actions: {
        submit: "Uložit recept",
        clearImages: "Odebrat obrázky",
      },
      aria: {
        removeIngredient: "Odebrat ingredienci",
        removeStep: "Odebrat krok",
      },
      titles: {
        remove: "Odebrat",
      },
      units: {
        GRAM: "g",
        KILOGRAM: "kg",
        MILLILITER: "ml",
        LITER: "l",
        OZ: "oz",
        LB: "lb",
        FL_OZ: "fl oz",
        CUP: "hrnek",
        TABLESPOON: "lžíce",
        TEASPOON: "lžička",
        PINCH: "špetka",
        PIECE: "ks",
        TO_TASTE: "podle chuti",
      },
      categoryCodes: {
        BREAKFAST: "Snídaně",
        LUNCH: "Oběd",
        DINNER: "Večeře",
        SOUP: "Polévky",
        MAIN_COURSE: "Hlavní chody",
        SIDE_DISH: "Přílohy",
        SALAD: "Saláty",
        SNACK: "Svačiny",
        DESSERT: "Dezerty",
        BAKERY: "Pečivo",
        DRINK: "Nápoje",
        SMOOTHIE: "Smoothie",
        SAUCE: "Omáčky",
        VEGETARIAN: "Vegetariánské",
        VEGAN: "Veganské",
        GLUTEN_FREE: "Bezlepkové",
        QUICK_MEAL: "Rychlá jídla",
        HEALTHY: "Zdravá výživa",
        BBQ: "Grilování",
        PASTA: "Těstoviny",
      },
    },
  },
  auth: {
    login: {
      title: "Přihlášení",
      usernameLabel: "Uživatelské jméno",
      usernamePlaceholder: "Zadejte uživatelské jméno",
      passwordLabel: "Heslo",
      passwordPlaceholder: "Zadejte heslo",
      submit: "Přihlásit se",
      loading: "Přihlašuji...",
      errorInvalid: "Neplatné přihlašovací údaje.",
      noAccount: "Nemáte účet?",
      goRegister: "Zaregistrujte se",
    },
    register: {
      title: "Registrace",
      emailLabel: "Email",
      emailPlaceholder: "Zadejte email",
      usernameLabel: "Uživatelské jméno",
      usernamePlaceholder: "Zadejte uživatelské jméno",
      passwordLabel: "Heslo",
      passwordPlaceholder: "Zadejte heslo",
      submit: "Zaregistrovat se",
      loading: "Registruji...",
      errorGeneric: "Registrace se nepodařila. Zkuste jiné údaje.",
      haveAccount: "Už máte účet?",
      goLogin: "Přihlaste se",
    },
  },
  recipeDetail: {
    actions: {
      back: "Zpět",
      addToFavorites: "Přidat do oblíbených",
      removeFromFavorites: "Odebrat z oblíbených",
      sendComment: "Odeslat",
      imperial: "Imperiální",
      metric: "Metrické",
    },
    sections: {
      photos: "Fotky",
      comments: "Komentáře",
    },
    fields: {
      rating: "Hodnocení",
      comment: "Komentář",
    },
    placeholders: {
      comment: "Napište komentář…",
    },
    hints: {
      noPhotos: "Zatím žádné fotky 😭",
      noComments: "Zatím žádné komentáře. Buďte první 😉",
      noDescription: "Tento recept zatím nemá popis.",
    },
    meta: {
      time: "Doba",
      minutes: "min",
      servings: "Porce",
      noRating: "Bez hodnocení",
      you: "Vy",
      commentsCount: (n: number) => `${n} komentářů`,
    },
    aria: {
      thumbAlt: (n: number) => `Otevřít fotku ${n}`,
      mainPhotoAlt: (title: string) => `Fotka receptu: ${title}`,
    },
    errors: {
      invalidId: "Neplatné ID receptu",
      notFound: "Recept nebyl nalezen",
    },
  },
  profile: {
    title: "Můj profil",
    aboutTitle: "O mně",
    aboutText: "Vítejte na své profilové stránce.",
    statsTitle: "Statistiky",
    myRecipes: "Moje recepty",
    favoriteRecipes: "Oblíbené",
    savedRecipes: "Uložené recepty",
    actions: "Akce",
    editProfile: "Upravit profil",
    settings: "Nastavení",
    logout: "Odhlásit se",
    loading: "Načítání profilu...",
    loadError: "Profil se nepodařilo načíst.",
    noRecipes: "Zatím nemáte žádné recepty.",
    joined: "Na platformě od",
    updated: "Naposledy upraveno",
  },
  settings: {
    title: "Nastavení",
    profileSection: "Informace o profilu",
    preferencesSection: "Předvolby",
    unitLabel: "Měrné jednotky",
    unitMetric: "Metrické (g, kg, ml)",
    unitImperial: "Imperiální (oz, lb, hrnky)",
    saveBtn: "Uložit změny",
    success: "Nastavení bylo úspěšně uloženo!",
    error: "Chyba při ukládání nastavení",
    name: "Jmeno",
    surname: "Příjmení",
    description: "Popis profilu",
    avatarUrl: "Profilová fotka",
    uploadPhoto: "Nahrát obrazek"
  },
};
