export const TEXTS_CZ = {
  header: {
    logoSubtext: "online kuchařka",
    loginButton: "Přihlásit se",
    languageCz: "CZ",
    languageEn: "EN",
  },
  navigation: {
    recipes: "Domů",
    categories: "Kategorie",
    create: "Vytvořit recept",
    favorites: "Oblíbené",
    my: "Moje recepty",
  },
  hero: {
    title: "Už vás nebaví vymýšlet, ",
    titleAccent: "co vařit?",
    titleSubtext: "Podívejte se na recepty nebo přidejte svůj vlastní!",
  },
  categories: {
    title: "Recepty",
    search: "Hledat",
    filters: "Filtry",
    categories: "Kategorie",
    diet: "Stravování",
    time: "Doba přípravy",
    score: "Hodnocení",
    clearFilters: "Zrušit filtry",
    applyFilters: "Použít filtry",
  },
  tags: {
    breakfast: "Snídaně",
    lunch: "Oběd",
    dinner: "Večeře",
    desserts: "Dezerty",
    snacks: "Svačiny",
    vegan: "Vegan",
    vegeterian: "Vegetariánské",
    glutenFree: "Bezlepkové",
  },
  preparationTime: {
    upTo15: "Do 15 minut",
    upTo30: "Do 30 minut",
    moreThan30: "Více než 30 minut",
  },
  rating: {
    more: "a více",
  },
  createRecipe: {
    createRecipe: "Vytvořit recept",
    form: {
      sections: {
        basic: "Základní informace",
        ingredients: "Ingredience",
        steps: "Postup",
        images: "Obrázky",
      },
      fields: {
        name: "Název receptu",
        description: "Popis",
        time: "Doba přípravy (min)",
        servings: "Počet porcí",
        category: "Kategorie",
        uploadImages: "Nahrát obrázky",
      },
      placeholders: {
        name: "Např. Krémové těstoviny s houbami",
        description: "Krátký popis receptu",
        category: "Vyberte kategorii",
        ingredient: "Např. 200 g těstovin",
        step: "Krok",
        amount: "Množství",
        unit: "Jednotka",
        ingredientName: "Např. těstoviny",
      },
      hints: {
        ingredients:
          "Tip: přidejte jednu položku na řádek — nové pole se objeví automaticky 😉",
        imagesEmpty: "PNG/JPG/WebP",
        imagesSelected: "Vybráno souborů",
      },
      actions: {
        submit: "Uložit recept",
        clearImages: "Odebrat obrázky",
      },
      aria: {
        removeIngredient: "Odebrat ingredienci",
        removeStep: "Odebrat krok",
      },
      titles: {
        remove: "Odebrat",
      },
      units: {
        GRAM: "g",
        KILOGRAM: "kg",
        MILLILITER: "ml",
        LITER: "l",
        TEASPOON: "lžička",
        TABLESPOON: "lžíce",
        CUP: "hrnek",
        PIECE: "ks",
      },
    },
  },
  auth: {
    login: {
      title: "Přihlášení",
      usernameLabel: "Uživatelské jméno",
      usernamePlaceholder: "Zadejte uživatelské jméno",
      passwordLabel: "Heslo",
      passwordPlaceholder: "Zadejte heslo",
      submit: "Přihlásit se",
      loading: "Přihlašuji...",
      errorInvalid: "Neplatné přihlašovací údaje.",
      noAccount: "Nemáte účet?",
      goRegister: "Zaregistrujte se",
    },
    register: {
      title: "Registrace",
      usernameLabel: "Uživatelské jméno",
      usernamePlaceholder: "Zadejte uživatelské jméno",
      passwordLabel: "Heslo",
      passwordPlaceholder: "Zadejte heslo",
      submit: "Zaregistrovat se",
      loading: "Registruji...",
      errorGeneric: "Registrace se nepodařila. Zkuste jiné údaje.",
      haveAccount: "Už máte účet?",
      goLogin: "Přihlaste se",
    },
  },
};
