export const TEXTS_EN = {
  header: {
    logoSubtext: "online cookbook",
    loginButton: "Log in",
    languageCz: "CZ",
    languageEn: "EN",
  },
  navigation: {
    recipes: "Home",
    categories: "Categories",
    create: "Create recipe",
    favorites: "Favorites",
    my: "My recipes",
  },
  hero: {
    title: "Tired of thinking about ",
    titleAccent: "what to cook?",
    titleSubtext: "Browse recipes or add your own!",
  },
  categories: {
    title: "Recipes",
    search: "Search",
    filters: "Filters",
    categories: "Categories",
    diet: "Diet",
    time: "Preparation time",
    score: "Rating",
    clearFilters: "Clear filters",
    applyFilters: "Apply filters",
  },
  tags: {
    breakfast: "Breakfast",
    lunch: "Lunch",
    dinner: "Dinner",
    desserts: "Desserts",
    snacks: "Snacks",
    vegan: "Vegan",
    vegeterian: "Vegetarian",
    glutenFree: "Gluten-free",
  },
  preparationTime: {
    upTo15: "Up to 15 minutes",
    upTo30: "Up to 30 minutes",
    moreThan30: "More than 30 minutes",
  },
  rating: {
    more: "and more",
  },
  createRecipe: {
    createRecipe: "Create recipe",
    form: {
      sections: {
        basic: "Basic info",
        ingredients: "Ingredients",
        steps: "Preparation steps",
        images: "Images",
      },
      fields: {
        name: "Recipe name",
        description: "Description",
        time: "Preparation time (min)",
        servings: "Servings",
        category: "Category",
        uploadImages: "Upload images",
      },
      placeholders: {
        name: "e.g. Creamy mushroom pasta",
        description: "Short description of the recipe",
        category: "Select category",
        ingredient: "e.g. 200 g pasta",
        step: "Step",
        amount: "Amount",
        unit: "Unit",
        ingredientName: "e.g. pasta",
      },
      hints: {
        ingredients:
          "Tip: add one per line — a new field appears automatically 😉",
        imagesEmpty: "PNG/JPG/WebP",
        imagesSelected: "File(s) selected",
      },
      actions: {
        submit: "Save recipe",
        clearImages: "Remove images",
      },
      aria: {
        removeIngredient: "Remove ingredient",
        removeStep: "Remove step",
      },
      titles: {
        remove: "Remove",
      },
      units: {
        GRAM: "g",
        KILOGRAM: "kg",
        MILLILITER: "ml",
        LITER: "l",
        TEASPOON: "tsp",
        TABLESPOON: "tbsp",
        CUP: "cup",
        PIECE: "pcs",
      },
    },
  },
  auth: {
    login: {
      title: "Log in",
      usernameLabel: "Username",
      usernamePlaceholder: "Enter your username",
      passwordLabel: "Password",
      passwordPlaceholder: "Enter your password",
      submit: "Log in",
      loading: "Logging in...",
      errorInvalid: "Invalid credentials.",
      noAccount: "Don't have an account?",
      goRegister: "Sign up",
    },
    register: {
      title: "Sign up",
      usernameLabel: "Username",
      usernamePlaceholder: "Choose a username",
      passwordLabel: "Password",
      passwordPlaceholder: "Choose a password",
      submit: "Create account",
      loading: "Signing up...",
      errorGeneric: "Registration failed. Try different credentials.",
      haveAccount: "Already have an account?",
      goLogin: "Log in",
    },
  },
};
