export const TEXTS_EN = {
  header: {
    logoSubtext: "online cookbook",
    loginButton: "Log in",
    languageCz: "CZ",
    languageEn: "EN",
    profileButton: "Profile",
  },
  navigation: {
    recipes: "Home",
    categories: "Categories",
    create: "Create recipe",
    favorites: "Favorites",
    my: "My recipes",
  },
  hero: {
    title: "Tired of thinking about ",
    titleAccent: "what to cook?",
    titleSubtext: "Browse recipes or add your own!",
  },
  categories: {
    title: "Recipes",
    search: "Search",
    filters: "Filters",
    categories: "Categories",
    diet: "Diet",
    time: "Preparation time",
    score: "Rating",
    clearFilters: "Clear filters",
    applyFilters: "Apply filters",
  },
  tags: {
    breakfast: "Breakfast",
    lunch: "Lunch",
    dinner: "Dinner",
    desserts: "Desserts",
    snacks: "Snacks",
    vegan: "Vegan",
    vegeterian: "Vegetarian",
    glutenFree: "Gluten-free",
  },
  preparationTime: {
    upTo15: "Up to 15 minutes",
    upTo30: "Up to 30 minutes",
    moreThan30: "More than 30 minutes",
  },
  rating: {
    more: "and more",
  },
  createRecipe: {
    createRecipe: "Create recipe",
    form: {
      sections: {
        basic: "Basic info",
        ingredients: "Ingredients",
        steps: "Preparation steps",
        images: "Images",
      },
      fields: {
        name: "Recipe name",
        description: "Description",
        time: "Preparation time (min)",
        servings: "Servings",
        category: "Category",
        uploadImages: "Upload images",
      },
      placeholders: {
        name: "e.g. Creamy mushroom pasta",
        description: "Short description of the recipe",
        category: "Select category",
        ingredient: "e.g. 200 g pasta",
        step: "Step",
        amount: "Amount",
        unit: "Unit",
        ingredientName: "e.g. pasta",
      },
      hints: {
        ingredients:
          "Tip: add one per line — a new field appears automatically 😉",
        imagesEmpty: "PNG/JPG/WebP",
        imagesSelected: "File(s) selected",
      },
      actions: {
        submit: "Save recipe",
        clearImages: "Remove images",
      },
      aria: {
        removeIngredient: "Remove ingredient",
        removeStep: "Remove step",
      },
      titles: {
        remove: "Remove",
      },
      units: {
        GRAM: "g",
        KILOGRAM: "kg",
        MILLILITER: "ml",
        LITER: "l",
        OZ: "oz",
        LB: "lb",
        FL_OZ: "fl oz",
        CUP: "cups",
        TABLESPOON: "tbsp",
        TEASPOON: "tsp",
        PINCH: "pinch",
        PIECE: "pcs",
        TO_TASTE: "to taste",
      },
      categoryCodes: {
        BREAKFAST: "Breakfast",
        LUNCH: "Lunch",
        DINNER: "Dinner",
        SOUP: "Soups",
        MAIN_COURSE: "Main Courses",
        SIDE_DISH: "Side Dishes",
        SALAD: "Salads",
        SNACK: "Snacks",
        DESSERT: "Desserts",
        BAKERY: "Bakery",
        DRINK: "Drinks",
        SMOOTHIE: "Smoothies",
        SAUCE: "Sauces",
        VEGETARIAN: "Vegetarian",
        VEGAN: "Vegan",
        GLUTEN_FREE: "Gluten-Free",
        QUICK_MEAL: "Quick Meals",
        HEALTHY: "Healthy Food",
        BBQ: "BBQ & Grill",
        PASTA: "Pasta",
      },
    },
  },
  auth: {
    login: {
      title: "Log in",
      usernameLabel: "Username",
      usernamePlaceholder: "Enter your username",
      passwordLabel: "Password",
      passwordPlaceholder: "Enter your password",
      submit: "Log in",
      loading: "Logging in...",
      errorInvalid: "Invalid credentials.",
      noAccount: "Don't have an account?",
      goRegister: "Sign up",
    },
    register: {
      title: "Sign up",
      emailLabel: "Email",
      emailPlaceholder: "Choose an email",
      usernameLabel: "Username",
      usernamePlaceholder: "Choose a username",
      passwordLabel: "Password",
      passwordPlaceholder: "Choose a password",
      submit: "Create account",
      loading: "Signing up...",
      errorGeneric: "Registration failed. Try different credentials.",
      haveAccount: "Already have an account?",
      goLogin: "Log in",
    },
  },
  recipeDetail: {
    actions: {
      back: "Back",
      addToFavorites: "Add to favorites",
      removeFromFavorites: "Remove from favorites",
      sendComment: "Send",
      imperial: "Imperial",
      metric: "Metric",
      loading: "Loading recipe...",
      deleteRecipe: "Delete",
      editRecipe: "Edit recipe",
      shoppingList: "Shopping list",
      download: "Download",
      copy: "Copy",
      close: "Close"
    },
    sections: {
      photos: "Photos",
      comments: "Comments",
    },
    fields: {
      rating: "Rating",
      comment: "Comment",
    },
    placeholders: {
      comment: "Write a comment…",
    },
    hints: {
      noPhotos: "No photos yet 😭",
      noComments: "No comments yet. Be the first 😉",
      noDescription: "This recipe has no description yet.",
      deleteRecipe: "Are you sure you want to delete this recipe?",
      commentPlaceholder: "Write a comment...",
      noDate: "—"
    },
    meta: {
      time: "Time",
      minutes: "min",
      servings: "Servings",
      noRating: "No rating",
      you: "You",
      author: "Author",
      commentsCount: (n: number) => `${n} comments`,
    },
    aria: {
      thumbAlt: (n: number) => `Open photo ${n}`,
      mainPhotoAlt: (title: string) => `Recipe photo: ${title}`,
    },
    errors: {
      invalidId: "Invalid recipe id",
      notFound: "Recipe not found",
      generic: "An error occurred",
      copyFailed: "Copy failed",
      deleteFailed: "Delete failed",
      updateFailed: "Update failed"
    },
  },
  profile: {
    title: "My Profile",
    aboutTitle: "About me",
    aboutText: "Welcome to your personal profile page.",
    statsTitle: "Statistics",
    myRecipes: "My recipes",
    favoriteRecipes: "Favorites",
    savedRecipes: "Saved recipes",
    actions: "Actions",
    editProfile: "Edit profile",
    settings: "Settings",
    logout: "Log out",
    loading: "Loading profile...",
    loadError: "Failed to load page.",
    noRecipes: "You have no recipes yet.",
    joined: "Joined",
    updated: "Last updated",
  },
  settings: {
    title: "Settings",
    profileSection: "Profile Information",
    preferencesSection: "Preferences",
    unitLabel: "Measurement Units",
    unitMetric: "Metric (g, kg, ml)",
    unitImperial: "Imperial (oz, lb, cups)",
    saveBtn: "Save Changes",
    success: "Settings saved successfully!",
    error: "Error while saving settings",
    name: "First name",
    surname: "Last name",
    description: "Profile description",
    avatarUrl: "Profile photo",
    uploadPhoto: "Upload Photo",
  },
  editRecipe: {
    title: "Edit recipe",
  }
};